// --------------------------------------------------------------
// -                    Renewal Core Scripts                    -
// --------------------------------------------------------------

// Utilitarian functions used by many scripts.
npc: npc/re/other/Global_Functions.txt
npc: npc/re/other/global_npcs.txt

