/// ROS 2026 - SERVIDOR DE TREINO NPCS
npc: npc/custom/ROS2026/Classes.txt
npc: npc/custom/ROS2026/Armas.txt
npc: npc/custom/ROS2026/Armaduras.txt
npc: npc/custom/ROS2026/Cartas.txt
npc: npc/custom/ROS2026/reparador.txt
npc: npc/custom/ROS2026/consu.txt
npc: npc/custom/ROS2026/runas.txt
npc: npc/custom/ROS2026/flags.txt
npc: npc/custom/ROS2026/Arenasdetreino.txt
//npc: npc/custom/ROS2026/wall.txt
npc: npc/custom/ROS2026/Mercado.txt
npc: npc/custom/ROS2026/healer.txt
npc: npc/custom/ROS2026/resetadora.txt
npc: npc/custom/ROS2026/plagio.txt

//npc: npc/custom/funcs/func1.txt
/////////////////////////////////////////////

npc: npc/custom/ROS2026/arenas/teleport.txt
npc: npc/custom/ROS2026/arenas/arenas.txt













////////////////////////////////////////////////
//npc: npc/custom/ROS2026/Refinador.txt
//npc: npc/custom/kafras/kafras.txt
//npc: npc/custom/other/pvp.txt
////npc: npc/custom/RWCSERVER/warperinos/bio3.txt
//npc: npc/custom/RWCSERVER/arenasrwc/walltester.txt
//npc: npc/custom/RWCSERVER/sorteio de arenas.txt
//npc: npc/custom/RWCSERVER/Doppelganger 2.2.txt
//
//npc: npc/custom/RWCSERVER/arenadeteste.txt
//npc: npc/custom/RWCSERVER/avisos.txt
//npc: npc/custom/RWCSERVER/build_master.txt
//npc: npc/custom/RWCSERVER/curandeira_izlude.txt
//npc: npc/custom/RWCSERVER/curandeira_teams.txt
//npc: npc/custom/RWCSERVER/equipamentosrwc.txt
//npc: npc/custom/RWCSERVER/estilista_wo_cloth_color.txt
//npc: npc/custom/RWCSERVER/fluxo_de_caixa.txt
//npc: npc/custom/RWCSERVER/jobchanger7x7.txt
//npc: npc/custom/RWCSERVER/plagiadora.txt
//npc: npc/custom/RWCSERVER/reset_spectator_state.txt
//npc: npc/custom/RWCSERVER/restock.txt
//npc: npc/custom/RWCSERVER/spectator.txt
////
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_blue.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_red.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arenas_Alphas.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_red_2.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_blue_2.txt
//
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_01.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_01.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_02.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_03.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_04.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_05.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_06.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_07.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_08.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_09.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_10.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_11.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_12.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_13.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_14.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_15.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_16.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_17.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_18.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_18.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_19.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_20.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_21.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_22.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_23.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_24.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_25.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_26.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_27.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_28.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_29.txt
//npc: npc/custom/RWCSERVER/arenasrwc/Arena_RWC_30.txt
//npc: npc/custom/RWCSERVER/mapasarenas.txt


